### ISSUE TITLE
Is it supposed to parse expressions exactly as Latex does?

### ISSUE THREAD

**Issue by pesmith0** [amaraljt/LaTeXPy#10]
In [this example notebook](https://colab.research.google.com/drive/1Ngd4wNIEkw5jjAjwxavwV5PybXkWFRb0?usp=sharing#scrollTo=z7c1pxEz1D6d):

```
# display error with multiple digit number w/o brackets
l(r"""
$\frac 123 5?$
""",1)
```
The output is this:
<img width="196" alt="Screen Shot 2023-11-04 at 3 04 11 PM" src="https://github.com/amaraljt/LaTeXPy/assets/113214079/369ccf38-f5fe-4dac-bfe8-c625899fad78">

The comment suggests this is a display error, but it seems like LatexPy is interpreting the expression differently than Latex does. In Latex, when braces are not used, the 1 and the 2 are the two arguments of \frac, and the 3 and 5 are afterwards. It seems like LatexPy considers whitespace where Latex does not, so it uses 123 and 5 as the two arguments.

If it is intended for LatexPy to use the exact syntax of Latex, then this would be considered a bug in LatexPy.

**Comment by amaraljt** [comment]
Although, this is a bug that needs to be fixed, we have moved our focus towards parsing pseudocode for this semester, so if you could check out the prototype folder and test pseudocode parsing using the algpseudocodex typeset, that would be great!
