### ISSUE TITLE
Error during setup instructions Step 2

### ISSUE THREAD

**Issue by pesmith0** [amaraljt/LaTeXPy#9]
<img width="799" alt="Screen Shot 2023-11-04 at 2 41 01 PM" src="https://github.com/amaraljt/LaTeXPy/assets/113214079/ec29d912-687f-43ec-9011-b6cecf31d3fc">

It works if you replace the third line with ```execfile("LaTeXPy/src/LaTeXPy.py")``` or ```execfile("/content/LaTeXPy/src/LaTeXPy.py")```

**Comment by pesmith0** [comment]
The error also occurs on [this example notebook](https://colab.research.google.com/drive/1Ngd4wNIEkw5jjAjwxavwV5PybXkWFRb0?usp=sharing) linked in the README.

Edit: it seems like anyone who opens this link has editing privileges, so I fixed the error on that notebook.

**Comment by amaraljt** [comment]
Go into the prototype folder and follow the README there. Let me know if it's still not letting you clone into colab

**Comment by pesmith0** [comment]
The prototype instructions do work.

However, I will suggest to increase the visibility of the prototype on the main page of the repository. Because I saw the top-level README and all of the instructions and features and stuff, I completely didn't even notice the prototype until you pointed it out.
